
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-nour}"
    image: cybulde-data-processing
    platform: linux/amd64
    container_name: cybulde-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/cybulde-n-38a68ba55de1.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-nour}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-nour}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME:-nour}/.ssh
    ports:
      - 8888:8888
      - 8000:8000

    ipc: host
    init: true
    


