
services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-nour}"
    image: cybulde-data
    platform: linux/amd64
    container_name: cybulde-data-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-nour}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-nour}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME:-nour}/.ssh
    environment:
      - HYDRA_FULL_ERROR=1
    ports:
      - 8888:8888
    ipc: host
    init: true
    


